---
- name: Zammad | Include setup-debian.yml
  ansible.builtin.include_tasks:
    file: "setup-debian.yml"
  when: ansible_os_family == 'Debian'

- name: Zammad | Install Zammad
  ansible.builtin.package:
    name: zammad
    state: "{{ zammad_package_state }}"

- name: Zammad | Ensure Zammad services are running and set to start on boot.
  ansible.builtin.systemd:
    name: zammad
    state: "{{ zammad_service_state }}"
    enabled: "{{ zammad_service_enabled }}"

- name: Zammad | Disable default nginx configuration for zammad
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/zammad.conf"
    state: "absent"
  when: zammad_nginx_disable_default_web_server
  notify: Reload nginx

- name: Zammad | Include redis role
  ansible.builtin.include_role:
    name: geerlingguy.redis
  when: zammad_add_redis

- name: Zammad | Set redis environment var
  ansible.builtin.command: "zammad config:set REDIS_URL=redis://127.0.0.1:6379"
  register: output
  changed_when: output.rc != 0
  when: zammad_add_redis
