---

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Zammad | Install Zammad
  package:
    name: zammad
    state: "{{ zammad_package_state }}"

- name: Zammad | Ensure Zammad services are running and set to start on boot.
  systemd:
    name: zammad
    state: "{{ zammad_service_state }}"
    enabled: "{{ zammad_service_enabled }}"

- name: Zammad | Disable default nginx configuration for zammad
  file:
    path: "/etc/nginx/sites-enabled/zammad.conf"
    state: "absent"
  when: "zammad_nginx_disable_default_web_server == true"
  notify: reload nginx

- name: Zammad | Include redis role
  include_role:
    name: geerlingguy.redis
  when: "zammad_add_redis == true"

- name: Zammad | Set redis environment var
  shell: "zammad config:set REDIS_URL=redis://127.0.0.1:6379"
  when: "zammad_add_redis == true"
