---

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Zammad | Install Zammad
  package:
    name: zammad
    state: "{{ zammad_package_state }}"

# - name: Zammad | Lower Priority from elasticsearch repo (do not trust that repo for anything different)
#   template:
#     src: ./files/elasticsearch_policy_100
#     dest: /etc/apt/preferences.d/elasticsearch_policy_100
#     owner: root
#     group: root
#     mode: 0644

- name: Zammad | Ensure Zammad services are running and set to start on boot.
  systemd:
    name: zammad
    state: "{{ zammad_service_state }}"
    enabled: "{{ zammad_service_enabled }}"


- name: Zammad | Disable default nginx server page to make zammad default web page
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: "absent"
  when: "zammad_nginx_disable_default_web_server == true"
  notify: reload nginx