---
- name: Zammad | Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - gnupg

- name: Zammad | Ensure Zammad apt key is present
  apt_key:
    url: https://dl.packager.io/srv/zammad/zammad/key
    state: present

# - name: Zammad | Ensure elk apt key is present
#   apt_key:
#     url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
#     state: present

- name: Zammad | Ensure Zammad apt repository is present
  apt_repository:
    repo: deb [arch=amd64] https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 11 main
    update_cache: yes
    state: present

# - name: Zammad | Ensure elk apt repository is present
#   apt_repository:
#     repo: deb [arch=amd64] https://artifacts.elastic.co/packages/7.x/apt stable main
#     update_cache: yes
#     state: present

- name: Zammad | Lower Priority from Zammad repo (do not trust that repo for anything different)
  template:
    src: ./files/zammad_policy_100
    dest: /etc/apt/preferences.d/zammad_policy_100
    owner: root
    group: root
    mode: 0644

# - name: Zammad | Lower Priority from ELK repo (do not trust that repo for anything different)
#   template:
#     src: ./files/elk_policy_100
#     dest: /etc/apt/preferences.d/elk_policy_100
#     owner: root
#     group: root
#     mode: 0644

- name: Zammad | Install Zammad
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - zammad

- name: Zammad | Ensure Zammad services are running and set to start on boot.
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - zammad
