---
- name: Zammad | Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - gnupg

- name: Zammad | Ensure Zammad apt key is present
  apt_key:
    url: https://dl.packager.io/srv/zammad/zammad/key
    state: present

- name: Zammad | Ensure Zammad apt repository is present
  apt_repository:
    repo: "deb [arch=amd64] https://dl.packager.io/srv/deb/zammad/zammad/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_version }} main"
    update_cache: yes
    state: present

- name: Zammad | Lower Priority from Zammad repo (do not trust that repo for anything different)
  template:
    src: zammad_policy_100.j2
    dest: /etc/apt/preferences.d/zammad_policy_100
    owner: root
    group: root
    mode: 0644
